SELECT COUNT(*) 
FROM STUDENTS  
WHERE MARRIED = 'YES';

SELECT COUNT(*)
FROM STUDENTS  
WHERE HALL = 11 AND MARRIED = 'YES';

SELECT COUNT(*) 
FROM NON_STUDENTS 
WHERE ROLE='FACULTY';

SELECT COUNT(*) 
FROM NON_STUDENTS 
WHERE ROLE='STAFF';

SELECT COUNT(*) 
FROM STUDENTS;

SELECT 
(SELECT COUNT(DISTINCT MEMBER)
	FROM FAMILY_NON_STUDENTS) +
(SELECT COUNT(DISTINCT MEMBER) 
	FROM FAMILY_STUDENTS);

SELECT 
(SELECT COUNT(DISTINCT MEMBER) 
	FROM FAMILY_NON_STUDENTS) +
(SELECT COUNT(DISTINCT MEMBER)
  FROM FAMILY_STUDENTS) + 
(SELECT COUNT(*)
	FROM STUDENTS) + 
(SELECT COUNT(*)
  FROM NON_STUDENTS) ;

SELECT 
(SELECT COUNT(DISTINCT MEMBER) 
	FROM FAMILY_NON_STUDENTS)*(1.0)/(SELECT COUNT(*) 
																				FROM NON_STUDENTS 
																				WHERE ROLE='FACULTY');

SELECT  
  CASE WHEN (SELECT COUNT(DISTINCT HEAD))-(SELECT COUNT(HEAD)) == 0
  THEN 'NO'
  ELSE 'YES'
  END
FROM DEPARTMENTS;

SELECT 
(SELECT COUNT(*) 
	FROM STUDENTS
	WHERE UG_PG == 'UG' AND DEPT_ADVISOR IS NOT NULL)*100.0/(SELECT COUNT(*)
																														 FROM STUDENTS 
																														 WHERE UG_PG == 'UG') ;

SELECT COUNT(DISTINCT ADVISOR2) 
FROM (SELECT ADVISOR2 
				FROM STUDENTS 
				JOIN NON_STUDENTS 
				WHERE ADVISOR2 = NON_STUDENTS.ID AND NON_STUDENTS.DEPT != STUDENTS.DEPT);